### ISSUE TITLE
Prévenir le développeur de l'API des problèmes que vous avez identifié sur les départements identiques

### ISSUE THREAD

**Issue by annedm** [Vincent-Mouillot/Dashboard_Covid#2]
Déposez une issue sur le git, en détaillant précisément le pb avec capture d'écran, en précisant les api appelées, quel jour, pour quelles régions, etc...
https://github.com/florianzemma/CoronavirusAPI-France

**Comment by Vincent-Mouillot** [comment]
On vient de voir qu'il avait résolu le problème depuis l'envoi de notre projet, maintenant les données de tous les départements sont accessibles.
